stages:
  data_processing:
    cmd: kedro run --pipeline=data_processing
    deps:
      - data/01_raw/chile_completo_covid_2020.csv
      - data/01_raw/chile_completo_covid_2021.csv
      - data/01_raw/chile_completo_covid_2022.csv
      - src/spaceflights/pipelines/data_processing/
    outs:
      - data/05_model_input/regression_dataset.csv
      - data/05_model_input/classification_dataset.csv
    
  data_science:
    cmd: kedro run --pipeline=data_science
    deps:
      - data/05_model_input/regression_dataset.csv
      - data/05_model_input/classification_dataset.csv
      - src/spaceflights/pipelines/data_science/
    outs:
      - data/06_models/trained_regression_models.pkl
      - data/06_models/trained_classification_models.pkl
      - data/06_models/tuned_regression_results.pkl
      - data/06_models/tuned_classification_results.pkl
    metrics:
      - data/08_reporting/regression_metrics.json
      - data/08_reporting/classification_metrics.json
    plots:
      - data/08_reporting/feature_importance_analysis.json