# Hyperparameter tuning - ULTRA OPTIMIZADO
gridsearch_config:
  cv_folds: 3
  n_jobs: -1
  verbose: 0
  
  # Grids para REGRESIÓN
  regression_grids:
    random_forest:
      enabled: true
      param_grid:
        n_estimators: [100]
        max_depth: [10]
        min_samples_split: [5]
    
    gradient_boosting:
      enabled: false  # DESHABILITADO - demasiado lento
      param_grid:
        n_estimators: [100]
        learning_rate: [0.1]
        max_depth: [5]
    
    xgboost:
      enabled: true
      param_grid:
        n_estimators: [100]
        max_depth: [5]
        learning_rate: [0.1]
    
    ridge:
      enabled: true
      param_grid:
        alpha: [1.0, 10.0]
    
    lasso:
      enabled: true
      param_grid:
        alpha: [1.0, 10.0]
  
  # Grids para CLASIFICACIÓN
  classification_grids:
    random_forest:
      enabled: true
      param_grid:
        n_estimators: [100]
        max_depth: [10]
        class_weight: ['balanced']
    
    gradient_boosting:
      enabled: false  # DESHABILITADO - demasiado lento
      param_grid:
        n_estimators: [100]
        learning_rate: [0.1]
        max_depth: [5]
    
    logistic_regression:
      enabled: true
      param_grid:
        C: [1.0, 10.0]
        solver: ['lbfgs']
        max_iter: [2000]
    
    k_neighbors_classifier:
      enabled: true
      param_grid:
        n_neighbors: [3, 5, 7]