# =====================================================
# PARÁMETROS GENERALES DEL PROYECTO COVID-19
# =====================================================

# Parámetros para limpieza de datos
data_cleaning:
  date_format_2021: "%d-%m-%Y"
  missing_value_threshold: 0.5
  outlier_method: "iqr"
  outlier_factor: 1.5

# Parámetros para análisis temporal
temporal_analysis:
  seasonal_periods: [7, 30, 365]
  trend_window: 30
  peak_threshold_percentile: 0.9

# Parámetros para análisis regional
regional_analysis:
  top_regions_count: 15
  min_population_threshold: 10000