# Parameters for COVID-19 Chile Analysis Project

# Parámetros para limpieza de datos
data_cleaning:
  date_format_2021: "%d-%m-%Y"
  missing_value_threshold: 0.5
  outlier_method: "iqr"
  outlier_factor: 1.5

# Parámetros para feature engineering
feature_engineering:
  rolling_window_days: 7
  lag_days: [1, 3, 7, 14]
  percentiles_for_categorization: [0.25, 0.5, 0.75, 0.9]
  
# Parámetros para análisis temporal
temporal_analysis:
  seasonal_periods: [7, 30, 365]
  trend_window: 30
  peak_threshold_percentile: 0.9

# Parámetros para análisis regional
regional_analysis:
  top_regions_count: 15
  min_population_threshold: 10000
  
# Targets para Machine Learning
ml_targets:
  regression_targets:
    - "new_confirmed_next_7d"  # Casos próximos 7 días
    - "cumulative_confirmed_growth_rate"  # Tasa crecimiento acumulado
  classification_targets:
    - "high_transmission_period"  # Período alta transmisión (binario)
    - "alert_level"  # Nivel alerta (multiclase: bajo, medio, alto, crítico)